platform :osx, "10.9"

plugin 'cocoapods-keys', {
    :project => "GIFs",
    :keys => [
        "GiphyAPIKey",
        "RandoTwitterBotConsumerKey",
        "RandoTwitterBotConsumerSecret",
        "RandoTwitterBotOAuthToken",
        "RandoTwitterBotOAuthTokenSecret"
    ]
  }

target "GIFs" do
    pod 'StandardPaths', '~> 1.5.4'
    pod "GIFKit", :git => "https://github.com/orta/GIFKit.git"
    pod 'STTwitter', '~> 0.2'
end